name: keepass_one
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.10.0-290.4.beta

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.5+1

  cupertino_icons: ^1.0.8
  rust_lib_keepass_one:
    path: rust_builder
  flutter_rust_bridge: 2.11.1
  flutter_dotenv: ^6.0.0

  webdav_client: ^1.2.2
  dartssh2: ^2.13.0
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  dio: ^5.9.0

  drift: ^2.29.0
  drift_flutter: ^0.2.7
  path_provider: ^2.1.5
  collection: ^1.19.1

  drift_dev: ^2.29.0
  build_runner: ^2.9.0
  font_awesome_flutter: ^10.12.0
  flutter_hooks: ^0.21.3+1
  file_picker: ^10.3.3
  flutter_riverpod: ^2.6.1
  get_it: ^8.2.0
  shared_preferences: ^2.5.3


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  integration_test:
    sdk: flutter
  build_runner: ^2.9.0
  freezed: ^3.2.3
  json_serializable: ^6.11.1

flutter:
  uses-material-design: true
  assets:
    - .env
